# Generated by Django 3.0.7 on 2020-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('restoreEmail', models.EmailField(max_length=100, verbose_name='Restore Email')),
                ('mobilePhone', models.CharField(max_length=20, verbose_name='Mobile Phone')),
                ('countryAbbreviation', models.CharField(max_length=2, verbose_name='Country Abbreviation')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('lastUpdate', models.DateField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
