# Generated by Django 3.0.7 on 2020-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
